### ISSUE TITLE
How to use RGB DiVAE tokenizer?

### ISSUE THREAD

**Issue by shaibagon** [apple/ml-4m#22]
I am trying to encoe and decode RGB images using the trained DiVAE checkpoint:
```
from fourm.vq.vqvae import DiVAE
from fourm.utils import denormalize, IMAGENET_DEFAULT_MEAN, IMAGENET_DEFAULT_STD
from torchvision.transforms import Normalize


tok = DiVAE.from_pretrained('EPFL-VILAB/4M_tokenizers_rgb_16k_224-448')
normalize = Normalize(mean=IMAGENET_DEFAULT_MEAN, std=IMAGENET_DEFAULT_STD)
# encode
_, _, tokens = tok.encode(normalize(rgb_b3hw))
# decode
rgb_b3hw = denormalize(tok.decode_tokens(tokens))
```

For these input images:
![image](https://github.com/user-attachments/assets/d2a3c529-f202-43fe-9c47-2266e925247b)

I get these decoded images:
![image](https://github.com/user-attachments/assets/5c43a722-e35f-4184-907a-ab04d859196f)

I tried to use with and without RGB normalization - it did not make any significant change tot the quality of the reconstruction I get.

What am I doing wrong? How one should use the tokenizer?

Thank you,

**Comment by alexanderswerdlow** [comment]
Same question here!

**Comment by garjania** [comment]
Hi @shaibagon @alexanderswerdlow 

Regarding your script, the tokenizer was trained with the inputs normalized using `IMAGENET_INCEPTION_MEAN` and `IMAGENET_INCEPTION_STD` parameters. So for a correct tokenization/reconstruction, you should use these two values instead of the ImageNet ones in normalizing and denormalizing.

Note that the tokenizer only supports resolutions between 224 and 448, and it might not work for any resolution outside of this range. Also, you need to specify the image size as the decoder input. Since the RGB tokenizer uses a diffusion decoder, it needs the image size to sample the initial noise with the correct resolution. So overall the script should look like this:

```
from fourm.vq.vqvae import DiVAE
from fourm.utils import denormalize, IMAGENET_INCEPTION_MEAN, IMAGENET_INCEPTION_STD
from torchvision.transforms import Normalize

tok = DiVAE.from_pretrained('EPFL-VILAB/4M_tokenizers_rgb_16k_224-448').cuda()
normalize = Normalize(mean=IMAGENET_INCEPTION_MEAN, std=IMAGENET_INCEPTION_STD)

# encode
_, _, tokens = tok.encode(normalize(rgb_b3hw).cuda())

# decode
image_size = rgb_b3hw.shape[-1]
rgb_b3hw  = tok.decode_tokens(tokens, image_size=image_size)
rgb_b3hw = denormalize(rgb_b3hw, mean=IMAGENET_INCEPTION_MEAN, std=IMAGENET_INCEPTION_STD)
```

Another note is that by default, the diffusion decoder uses 1000 timesteps for decoding the tokens, which is unnecessary during inference. You can do it in 50 steps to make the decoding faster by passing the timesteps argument:

`tok.decode_tokens(tokens, image_size=image_size, timesteps=50)`

Hope this helps.

**Comment by shaibagon** [comment]
@garjania - works like a charm!
Using 50 diffusion steps:
![image](https://github.com/user-attachments/assets/af40d197-4c4b-41a1-9313-0520d62b1f7c)

Using full 1000 steps:
![image](https://github.com/user-attachments/assets/0e701e57-b1bc-49c3-baad-699114a9859f)
As you said - diffusion for 1000 steps does not make such a diference.
